// Generated by CoffeeScript 1.4.0
(function() {
  var App, http, redis;

  redis = require('redis-url').connect(process.env.REDISTOGO_URL || 'localhost');

  http = require('http');

  App = require('strata');

  App.use(App.commonLogger);

  App.use(App.contentType, 'application/json');

  App.use(App.contentLength);

  App.use(App.file, require('path').resolve('./public'), 'index.html');

  App.get('/v1/compliments', function(env, next) {
    var cacheKey;
    cacheKey = '/v1/compliments';
    return redis.get(cacheKey, function(error, compliments) {
      var data;
      if (compliments != null ? compliments.length : void 0) {
        return App.Response(compliments).send(next);
      } else {
        data = '';
        return http.get('http://emergencycompliment.com/js/compliments.js', function(response) {
          response.on('data', function(chunk) {
            return data += chunk;
          });
          return response.on('end', function() {
            eval(data.toString());
            compliments = JSON.stringify(compliments);
            redis.set(cacheKey, compliments);
            return App.Response(compliments).send(next);
          });
        });
      }
    });
  });

  App.run({
    port: process.env.PORT || 5294
  });

}).call(this);
